import { greeting } from '@/lib/domain/pitch';
import { briefText, type Brief } from './brief';

/**
 * Step 6: the quality gate (spec §14.2). PURE and DETERMINISTIC.
 *
 * "A prompt cannot be unit-tested; this can." Every check is ordinary code, and
 * it is the real defence against prompt injection too (§22.5): "the gate is the
 * real defence here, because it does not negotiate."
 *
 * A failure re-runs step 5 once with a stricter prompt that names what failed;
 * a second failure falls back to the template pitch (the `failed` render state).
 *
 * The gate judges what the prospect actually reads: the page's greeting ("Hi
 * Tom,") followed by the body. The model is told not to write a greeting,
 * because the page supplies one.
 *
 * Tuned to reject rather than to be generous. A false rejection costs one retry
 * and, at worst, the perfectly good template; a false pass puts an invented
 * price, a wrong name or a quoted personal note in front of a prospect.
 */

export type GateCheck =
  | 'empty'
  | 'references_problem'
  | 'echoes_note'
  | 'placeholder_or_tell'
  | 'competitor_framing'
  | 'reveals_research'
  | 'unsupported_price'
  | 'unsupported_claim'
  | 'length'
  | 'no_call_to_action'
  | 'wrong_name';

export type GateFailure = { check: GateCheck; detail: string };

export type GateResult = { pass: boolean; failures: GateFailure[]; words: number };

export const MIN_WORDS = 60;
export const MAX_WORDS = 180;

// ------------------------------------------------------------ text helpers

const STOPWORDS = new Set(
  (
    'a about above after again against all also am an and any are as at be because been before ' +
    'being below between both but by can could did do does doing down during each few for from ' +
    'further get got had has have having he her here hers herself him himself his how i if in into ' +
    'is it its itself just let like lot lots make many me more most much must my myself no nor not ' +
    'now of off on once one only or other our ours ourselves out over own really same she should so ' +
    'some such than that the their theirs them themselves then there these they this those through ' +
    'to too two under until up very was way we well were what when where which while who whom why ' +
    'will with would you your yours yourself yourselves loves love likes keen ' +
    'thing things time good great new day days week weeks year years'
  )
    // NOT stopwords, deliberately: "kids", "family", "football" and the like are
    // exactly what a note contains and exactly what the echo check must catch.
    .split(' '),
);

function words(text: string): string[] {
  return text.trim().split(/\s+/).filter(Boolean);
}

/** Lower-cased content words with a light stem, so "machines" matches "machine". */
function stems(text: string): Set<string> {
  const out = new Set<string>();
  for (const raw of text.toLowerCase().match(/[a-z0-9]+/g) ?? []) {
    if (raw.length < 4 || STOPWORDS.has(raw)) continue;
    out.add(raw.replace(/(ing|ies|es|ed|s)$/, '') || raw);
  }
  return out;
}

function intersect(a: Set<string>, b: Set<string>): string[] {
  return [...a].filter((x) => b.has(x));
}

// ----------------------------------------------------- the pattern checks

/** Unfilled templates and the tells that make a note read as machine-written (§4). */
const TELLS: readonly [RegExp, string][] = [
  [/\[[^\]\n]{1,60}\]/, 'square-bracket placeholder'],
  [/\{\{?[^}\n]{1,60}\}?\}/, 'curly-brace placeholder'],
  [/<\/?[a-z][^>]*>/i, 'markup'],
  [/\bas an ai\b|\bi(?:'m| am) an ai\b/i, 'announces the AI'],
  [/\b(?:large )?language model\b|\bai[- ]generated\b|\bgenerated by\b/i, 'announces the AI'],
  [/\bi hope (?:this|my) (?:email|message|note) finds you\b/i, 'template opener'],
  [/\bi hope (?:you are|you're|all is) (?:well|doing well)\b/i, 'template opener'],
  [/\bdear (?:sir|madam|sir\/madam)\b/i, 'template opener'],
  [
    /\b(?:lorem ipsum|your name here|company name|prospect name|placeholder)\b/i,
    'placeholder text',
  ],
  [/\b(?:TBD|TODO|XXX)\b/, 'placeholder text'],
];

/** §14.4: research deep, say less. Never frame the note around competitors. */
const COMPETITORS = /\b(?:competitors?|competition|rivals?)\b/i;

/**
 * Saying HOW we know something turns specificity into surveillance (§4, §14.4).
 * The facts can be used; announcing the research cannot.
 */
const REVEALS_RESEARCH = new RegExp(
  [
    // Announcing the research itself.
    String.raw`\b(?:i|we) (?:looked (?:you|your \w+) up|looked into you|researched|googled|dug into|did (?:some|a bit of) (?:research|digging)|came across)\b`,
    // Any reference to their web presence. A follow-up note has no reason to
    // mention it. "Site" alone is NOT matched: in plant hire and construction,
    // "your site team" is ordinary language, not a tell.
    String.raw`\byour (?:website|web ?site|homepage|home page|linkedin|online presence)\b`,
  ].join('|'),
  'i',
);

const PRICE =
  /(?:[£$€]\s?\d[\d,]*(?:\.\d+)?\s?[km]?\b)|(?:\b\d[\d,]*(?:\.\d+)?\s?(?:pounds|gbp|usd|dollars|euros?)\b)/gi;
const PERCENT = /\b\d{1,3}(?:\.\d+)?\s?%/g;

/** Claims a business must be able to back up. Allowed only if the brief says so. */
const CLAIMS =
  /\b(?:guarantee[sd]?|certified|accredited|award[- ]winning|iso ?\d{4,5}|market[- ]leading|industry[- ]leading|number one|best[- ]in[- ]class|world[- ]class)\b/gi;

const CALL_TO_ACTION =
  /\b(?:book|schedule|pick a (?:time|slot)|grab a (?:time|slot)|find a time|(?:15|fifteen)[- ]minute|15 minutes|fifteen minutes|quick call|short call|a call)\b/i;

/**
 * Frequent first names, for spotting a stranger's name in the pitch. Names that
 * are also ordinary words (Will, Mark, Grace, Rose, Bill, May, Frank...) are left
 * out on purpose: this list must never reject a sentence for using English.
 */
const FIRST_NAMES = new Set(
  (
    'James John Robert Michael David Richard Joseph Thomas Charles Christopher Daniel Matthew ' +
    'Anthony Donald Steven Paul Andrew Joshua Kenneth Kevin Brian George Timothy Ronald Edward ' +
    'Jason Jeffrey Ryan Jacob Gary Nicholas Eric Jonathan Stephen Larry Justin Scott Brandon ' +
    'Benjamin Samuel Gregory Alexander Patrick Jack Dennis Jerry Tyler Aaron Henry Adam Nathan ' +
    'Peter Zachary Kyle Noah Ethan Jeremy Christian Keith Roger Terry Sean Austin Arthur Lawrence ' +
    'Jesse Dylan Bryan Joe Jordan Albert Logan Oliver Harry Charlie Oscar Alfie Leo Freddie Archie ' +
    'Tom Tommy Dan Danny Ben Sam Mike Chris Nick Matt Steve Dave Rob Andy Pete Tony Jim Jimmy ' +
    'Mary Patricia Jennifer Linda Elizabeth Barbara Susan Jessica Sarah Karen Lisa Nancy Betty ' +
    'Margaret Sandra Ashley Kimberly Emily Donna Michelle Carol Amanda Dorothy Melissa Deborah ' +
    'Stephanie Rebecca Sharon Laura Cynthia Kathleen Amy Angela Shirley Anna Brenda Pamela Emma ' +
    'Nicole Helen Samantha Katherine Christine Debra Rachel Carolyn Janet Catherine Maria Heather ' +
    'Diane Julie Olivia Victoria Kelly Christina Lauren Joan Evelyn Judith Megan Cheryl Andrea ' +
    'Hannah Martha Jacqueline Gloria Teresa Ann Sara Madison Kathryn Janice Jean Abigail Alice ' +
    'Judy Sophia Denise Amelia Isla Ava Mia Ella Lily Isabella Poppy Freya Chloe Jess Kate Katie ' +
    'Priya Raj Ahmed Mohammed Muhammad Ali Fatima Aisha Omar Hassan Ravi Sanjay Wei Chen Yuki'
  ).split(/\s+/),
);

// ------------------------------------------------------- shared claim checks

/**
 * Checks 3 and 4 of the gate, for any text the prospect reads: no placeholders or
 * tells, no competitor framing, never announcing the research, and no price,
 * percentage or credential that `context` does not contain.
 *
 * Shared by the pitch gate and the chatbot's reply check (§18.2: "no invented
 * pricing, no invented capabilities"), so both enforce the same rules.
 *
 * @param context  all the text the writer was allowed to draw on
 * @param pricing  the business's pricing; with none, ANY price is unsupported
 */
export function claimFailures(
  text: string,
  context: string,
  pricing: string | null,
): GateFailure[] {
  const failures: GateFailure[] = [];
  const fail = (check: GateCheck, detail: string) => failures.push({ check, detail });

  for (const [pattern, label] of TELLS) {
    if (pattern.test(text)) fail('placeholder_or_tell', label);
  }

  // §14.4 and §4: no competitor framing, and never announce the research.
  if (COMPETITORS.test(text)) fail('competitor_framing', 'mentions competitors');
  if (REVEALS_RESEARCH.test(text)) fail('reveals_research', 'says how we know about them');

  const contextDigits = (context.match(/\d[\d,.]*/g) ?? []).map((d) => d.replace(/[,.]/g, ''));
  for (const price of text.match(PRICE) ?? []) {
    const digits = price.replace(/[^\d]/g, '');
    if (!pricing || !contextDigits.includes(digits)) {
      fail('unsupported_price', `quotes ${price.trim()}, which is not in the pricing`);
    }
  }
  for (const percent of text.match(PERCENT) ?? []) {
    const digits = percent.replace(/[^\d.]/g, '').replace(/\./g, '');
    if (!contextDigits.includes(digits)) {
      fail('unsupported_claim', `states ${percent.trim()}, which nothing in the brief supports`);
    }
  }
  const lowerContext = context.toLowerCase();
  for (const claim of text.match(CLAIMS) ?? []) {
    if (!lowerContext.includes(claim.toLowerCase())) {
      fail('unsupported_claim', `claims "${claim}", which the business profile does not`);
    }
  }

  return failures;
}

// ----------------------------------------------------------------- the gate

export function qualityGate(body: string, brief: Brief): GateResult {
  const failures: GateFailure[] = [];
  const fail = (check: GateCheck, detail: string) => failures.push({ check, detail });

  const trimmed = body.trim();
  const count = words(trimmed).length;

  if (!trimmed) {
    return { pass: false, failures: [{ check: 'empty', detail: 'the pitch is empty' }], words: 0 };
  }

  // What the prospect reads: the page's greeting, then this body.
  const composed = `${greeting(brief.prospect.firstName)} ${trimmed}`;
  const context = briefText(brief);
  const contextStems = stems(context);
  const bodyStems = stems(trimmed);

  // 1. References the stated problem. A generic pitch is the failure mode the
  //    product exists to avoid.
  const problemStems = stems([...brief.problems, brief.customProblem ?? ''].join(' '));
  if (problemStems.size > 0 && intersect(problemStems, bodyStems).length === 0) {
    fail(
      'references_problem',
      `does not mention the problem they raised: "${brief.primaryProblem}"`,
    );
  }

  // 2. Does not echo the note. "You mentioned you support Arsenal" reads as
  //    surveillance. Words the note shares with the legitimate context (the
  //    problem, the company, the services) are not evidence of an echo.
  if (brief.toneNote) {
    const distinctive = [...stems(brief.toneNote)].filter((s) => !contextStems.has(s));
    const echoed = distinctive.filter((s) => bodyStems.has(s));
    if (echoed.length > 0) {
      fail('echoes_note', `repeats the private note (${echoed.join(', ')})`);
    }
  }

  // 3 and 4. No placeholders or tells, no competitor framing, never announce the
  //    research, and no prices, statistics or credentials the brief does not
  //    contain. Shared with the chatbot's reply check (§18.2).
  failures.push(...claimFailures(trimmed, context, brief.business.pricing));
  const lowerContext = context.toLowerCase();

  // 5. Length and shape: one screen on a phone, with a call to action.
  if (count < MIN_WORDS || count > MAX_WORDS) {
    fail('length', `${count} words; must be ${MIN_WORDS}-${MAX_WORDS}`);
  }
  if (!CALL_TO_ACTION.test(trimmed)) {
    fail('no_call_to_action', 'does not invite them to book a time');
  }

  // 6. Names the right person — the one mistake a prospect always notices.
  const allowed = new Set(
    [brief.prospect.firstName, brief.rep.firstName].filter(Boolean).map((n) => n!.toLowerCase()),
  );

  const salutations = [...trimmed.matchAll(/\b(?:hi|hello|hey|dear)\s+([A-Z][a-z]+)/g)];
  for (const [, name] of salutations) {
    if (!allowed.has(name!.toLowerCase())) fail('wrong_name', `addresses "${name}"`);
  }

  for (const token of trimmed.match(/\b[A-Z][a-z]+\b/g) ?? []) {
    if (
      FIRST_NAMES.has(token) &&
      !allowed.has(token.toLowerCase()) &&
      !lowerContext.includes(token.toLowerCase())
    ) {
      fail('wrong_name', `names "${token}", who is not the prospect`);
    }
  }

  if (brief.prospect.firstName && !composed.includes(brief.prospect.firstName)) {
    fail('wrong_name', `never names ${brief.prospect.firstName}`);
  }

  // One failure per distinct message is enough for the retry prompt.
  const unique = failures.filter(
    (f, i) => failures.findIndex((g) => g.check === f.check && g.detail === f.detail) === i,
  );

  return { pass: unique.length === 0, failures: unique, words: count };
}
